---
title: "homework_4_Ibeanusi"
author: "Nnenna Ibeanusi"
date: "7/1/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library("tidyverse")
#library("dplyr")
library("nycflights13")
```

```{r}
flights
```

```{r}
?flights
```




```{r}
# Come up with another approach that will give you the same output as not_cancelled %>% count(dest) and not_cancelled %>% count(tailnum, wt = distance) (without using count())
not_cancelled1 <- flights %>% count(dest)
not_cancelled1

not_cancelled <- flights %>% 
filter(!is.na(dep_delay), !is.na(arr_delay))

not_cancelled#display


again_not_cancelled <- not_cancelled %>% group_by(dest) %>% 
  summarize(
          n=n()
  )
again_not_cancelled

#try this code
not_cancelled2 <- not_cancelled %>% 
  group_by(dest) %>%
  summarise(n = sum(!is.na(dest))) 

not_cancelled2

not_cancelled3 <-not_cancelled%>% count(tailnum, wt = distance)
not_cancelled3

not_cancelled4 <- not_cancelled %>%
  group_by(tailnum) %>%
tally(wt = distance)

not_cancelled4
```

```{r}
#4Look at the number of cancelled flights per day. Is there a pattern? Is the proportion of cancelled flights related to the average delay?
#cancelled <- flights %>% 
#  filter(is.na(dep_delay), is.na(arr_delay))

#num_flights_per_day <- cancelled %>% group_by(year, month, day) #%>% summarise(n=sum(flight))
#num_flights_per_day

cancelled_delayed <- 
  flights %>%
  mutate(cancelled = (is.na(arr_delay) | is.na(dep_delay))) %>%
  group_by(year, month, day) %>%
  summarise(prop_cancelled = mean(cancelled),
            avg_dep_delay = mean(dep_delay, na.rm = TRUE))
cancelled_delayed
ggplot(cancelled_delayed, aes(x = avg_dep_delay, prop_cancelled)) +
  geom_point() +
  geom_smooth()
```

```{r}
#6What does the sort argument to count() do. When might you use it?
#the sort argument in count if true will sort output in descending order of n
not_cancelled %>% count(dest)
not_cancelled %>% count(dest,sort=T)
```

```{r}
#10.5.1
#How can you tell if an object is a tibble? (Hint: try printing mtcars, which is a regular data frame).
mtcars
```
```{r}
is_tibble(mtcars)#check if tibble
```

```{r}
as.tibble(mtcars)#can see what it looks like as a tible
```




```{r}
#10.5.2
#Compare and contrast the following operations on a data.frame and equivalent tibble. What is different? Why might the default data frame behaviours cause you frustration?
```
```{r}
#You can tell if an object is a tibble, as opposed to a dataframe, in that the class tible is printed, each column class is printed out below the variable name, and the trailing variable names are not printed out but only listed.
```

```{r}
df <- data.frame(abc = 1, xyz = "a")
df$x
df[, "xyz"]
df[, c("abc", "xyz")]
```


```{r}
#10.5.3
#If you have the name of a variable stored in an object, e.g. var <- "mpg", how can you extract the reference variable from a tibble?
tbl <- as.tibble(mtcars)
var <- "mpg"
tbl[[var]]
```

```{r}
#10.5.6
#What option controls how many additional column names are printed at the footer of a tibble?
?print.tbl_df
#the print function for the tible is print.tbl_df
#the n_extra determines the number of extra columns to print for
```

```{r}
#12.3.3
#2Why does this code fail?
#table4a %>% 
  #gather('1999', '2000', key = "year", value = "cases")
#> Error in inds_combine(.vars, ind_list): Position must be between 0 and n
table4a %>% 
  gather('1999', '2000', key = "year", value = "cases")
#need quotes around 1999 and 2000
```

```{r}
#12.3.3
#3
#Why does spreading this tibble fail? How could you add a new column to fix the problem?
```

```{r}
#spread(people, key, value) Error: Duplicate identifiers for rows (1, 3)
#Spreading the data frame fails because there are two rows with “age” for “Phillip Woods”. We would need to add another column with an indicator for the number observation it is,
# people <- tribble(
#   ~name,             ~key,    ~value, ~obs,
#   #-----------------|--------|------|------
#   "Phillip Woods",   "age",       45, 1,
#   "Phillip Woods",   "height",   186, 1,
#   "Phillip Woods",   "age",       50, 2,
#   "Jessica Cordero", "age",       37, 1,
#   "Jessica Cordero", "height",   156, 1
# )
# spread(people, key, value)
```

```{r}
#12.3.3#4
#Tidy the simple tibble below. Do you need to spread or gather it? What are the variables?
preg <- tribble(
  ~pregnant, ~male, ~female,
  "yes",     NA,    10,
  "no",      20,    12
)
gather(preg, 'male','female',key="gender", value="cases")
```

```{r}
# What do the extra and fill arguments do in separate()? Experiment with the various options for the following two toy datasets.
tibble(x = c("a,b,c", "d,e,f,g", "h,i,j")) %>% 
  separate(x, c("one", "two", "three"))
```



```{r}
tibble(x = c("a,b,c", "d,e", "f,g,i")) %>% 
  separate(x, c("one", "two", "three"))
```

```{r}
tibble(x = c("a,b,c", "d,e,f,g", "h,i,j"))
```

```{r}
tibble(x = c("a,b,c", "d,e,f,g", "h,i,j")) %>% 
  separate(x, c("one", "two", "three"),extra="merge")
```

```{r}
tibble(x = c("a,b,c", "d,e", "f,g,i"))
```

```{r}
tibble(x = c("a,b,c", "d,e", "f,g,i")) %>% 
  separate(x, c("one", "two", "three"),fill="left")
```


```{r}
# fill and extra dictate how extra or missing values in rows are delt with when making a table.

# If there’s an extra value (like having multiple rows with the minority of the rows having more values), then we can indicate whether to give a warning about beingh dropped, drop the value without warning, or merge the last two values together. Or we can fill the missing value with NA frrom the left or right.
```




