---
title: "Homework_2_Ibeanusi_Nnenna"
author: "Nnenna Ibeanusi"
date: "6/19/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#install tidyverse,  install.packages("tidyverse")


```{r}
library(tidyverse)
```

##3.2.4 Excercises


```{r}
#Run ggplot(data = mpg). What do you see?
#blank graph
ggplot(data=mpg)
```

```{r}
#How many rows are in mpg? How many columns?
#234 observations, ie rows
#11 variables, ie columns
glimpse(mpg)
```

```{r}
?mpg
#drv, f=front-wheel drive, r=rear wheel drive,4=4wd
```

```{r}
#Make a scatterplot of hwy vs cyl.
ggplot(data=mpg)+geom_point(mapping=aes(x=cyl, y=hwy))
```

```{r}
#What happens if you make a scatterplot of class vs drv? Why is the plot not useful?
#class is a categorical data
#the points overlap and so we only see if there were any variables with that combination of classes
ggplot(data=mpg)+geom_point(mapping=aes(x=drv, y=class))
```

#3.3.1 Excercises

```{r}
#What’s gone wrong with this code? Why are the points not blue?
#The points are not blue beause the "blue"is being interpretaed as a vector (c("blue")) to map an aesthetic, just like hwy or displ. To manually override a color, the mapping could be placed outside the aes, see the piece of code block following the one below.
ggplot(data = mpg) + geom_point(mapping = aes(x = displ, y = hwy, color = "blue"))
```

```{r}
ggplot(data=mpg)+geom_point(mapping=aes(x=displ,y=hwy),color="blue")
```

```{r}
#Which variables in mpg are categorical? Which variables are continuous? (Hint: type ?mpg to read the documentation for the dataset). How can you see this information when you run mpg?
#displ, cyl, cty, hwy are continuous variables, a good many of the rest look categorical
mpg
```

```{r}
#Map a continuous variable to color, size, and shape. How do these aesthetics behave differently for categorical vs. continuous variables?
#color maps the variable to the saturation of the color of a blue mark. Other mappings can be achieved with scale_color_continuous
ggplot(data=mpg)+geom_point(mapping=aes(x=displ, y=hwy, color=displ))
```

```{r}
#size maps the variable to the area of the mark scale_radius can be used to map to the radius
ggplot(data=mpg)+geom_point(mapping=aes(x=displ, y=hwy, size=displ))
```

```{r}
#does not work #shape can't take a continuous variable, because shapes aren't ordered #ggplot(data=mpg)+geom_point(mapping=aes(x=#displ, y=hwy, shape=displ)) #
```


```{r}
#What happens if you map the same variable to multiple aesthetics?
#You can represent a variable with multiple aesthetics with no trouble. For instance, using both shape and color for one discrete variable means that your polot with still be readable in black and white
ggplot(data=mpg)+geom_point(mapping=aes(x=displ, y=hwy, size=displ, color=displ))
```

```{r}
#What does the stroke aesthetic do? What shapes does it work with? (Hint: use ?geom_point)
#Stroke controls with the border, for shapes that have one
ggplot(data=mpg)+geom_point(aes(x=cty, y=hwy, stroke=displ), shape=21)
```


```{r}
#What happens if you map an aesthetic to something other than a variable name, like aes(colour = displ < 5)?
##Aesthetic mappings are treated as expressions to be evaluated in the context of the data argument, so this will evaluate the expression, and plot the result
ggplot(data=mpg)+geom_point(aes(x=cty, y=hwy, color=displ<5))
```


##3.5.1

```{r}
#Take the first faceted plot in this section:
#It is diffucult to resolve more than a dozen or so discrete colors, but we can have larger number of facets than that. On the one hand, facets can be haring to read at a glance, or if the cells being compared aren't lined up in the required required dimension. So in a situation like this, colors are probably better, but if we had more classes, or wanted to use color for a different variable, facets would come into their own 
ggplot(data=mpg)+geom_point(mapping=aes(x=displ, y=hwy))+facet_wrap(~class, nrow=2)
```

```{r}
#Read ?facet_wrap. What does nrow do? What does ncol do? What other options control the layout of the individual panels? Why doesn’t facet_grid() have nrow and ncol argument?
##In facet_wrap, nrow and ncol control the number of rows and columns, but in facet_grid these are implied by the faceting variables. dir also controls the placement of the individual panels, and so isn't an argument of facet_grid
```

#3.6.1
```{r}
#What geom would you use to draw a line chart? A boxplot? A histogram? An area chart?
ggplot(mtcars, aes(x=qsec, y=mpg)) + 
  geom_area(position = 'identity', alpha=0, colour='black') + coord_cartesian(xlim=c(min(mtcars$qsec)*1.1,max(mtcars$qsec)*0.9), ylim=c(2, max(mtcars$mpg)))
```

```{r}
#Run this code in your head and predict what the output will look like. Then, run the code in R and check your predictions.
#3 different lines based on color, with the drv variable
#scatter plot with all three colors
#3 line plots
ggplot(data = mpg, mapping = aes(x = displ, y = hwy, color = drv)) + 
  geom_point() + 
  geom_smooth(se = FALSE)

```

```{r}
#What does show.legend = FALSE do? What happens if you remove it? Why do you think I used it earlier in the chapter?
#doesn't show legend when you include the piece of code, when you remove it, the legen shows
ggplot(data = mpg) +geom_smooth(mapping = aes(x = displ, y = hwy, color = drv),show.legend = FALSE)
```

```{r}
#What does the se argument to geom_smooth() do?
#se specifies whether to add a translucent background showing the confidence interval.
```


```{r}
#Will these two graphs look different? Why/why not?
#They will look the same, the first piece of code is just a more concise way to arrange the code, the following code is just more enunciated in the code
ggplot(data = mpg, mapping = aes(x = displ, y = hwy)) + 
  geom_point() + 
  geom_smooth()

```

```{r}
ggplot() + 
  geom_point(data = mpg, mapping = aes(x = displ, y = hwy)) + 
  geom_smooth(data = mpg, mapping = aes(x = displ, y = hwy))
```

#3.7.1
```{r}
#What does geom_col() do? How is it different to geom_bar()?
#The geom_bar() is a more explicity way to make the bar graph
```


```{r}
#Look at the data graphics at the following link: What is a Data Scientist. Please briefly critique the designer’s choices. What works? What doesn’t work? What would you have done differently?
#They use graphics really well to paint the picture. They certainly make the story points clear. Could have used better color schema because black and blue are close. With a lot of discrete variables, could have made a matrix type schema to describe the data. 
```


